USE [master]
GO
/****** Object:  Database [ExportDB]    Script Date: 2015-03-04 4:12:22 PM ******/
CREATE DATABASE [ExportDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ExportDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\ExportDB.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ExportDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\ExportDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [ExportDB] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ExportDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ExportDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ExportDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ExportDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ExportDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ExportDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [ExportDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ExportDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ExportDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ExportDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ExportDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ExportDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ExportDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ExportDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ExportDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ExportDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ExportDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ExportDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ExportDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ExportDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ExportDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ExportDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ExportDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ExportDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [ExportDB] SET  MULTI_USER 
GO
ALTER DATABASE [ExportDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ExportDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ExportDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ExportDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [ExportDB] SET DELAYED_DURABILITY = DISABLED 
GO
USE [ExportDB]
GO
/****** Object:  Table [dbo].[Data]    Script Date: 2015-03-04 4:12:23 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Data](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[SerialNo] [text] NOT NULL,
	[Value] [decimal](18, 0) NOT NULL,
	[Time] [datetime] NOT NULL,
 CONSTRAINT [PK_Data] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
USE [master]
GO
ALTER DATABASE [ExportDB] SET  READ_WRITE 
GO
