USE [master]
GO
/****** Object:  Database [tulongest]    Script Date: 2015-03-04 3:31:04 PM ******/
CREATE DATABASE [tulongest]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'tulongest', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\tulongest.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'tulongest_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\tulongest_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [tulongest] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [tulongest].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [tulongest] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [tulongest] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [tulongest] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [tulongest] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [tulongest] SET ARITHABORT OFF 
GO
ALTER DATABASE [tulongest] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [tulongest] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [tulongest] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [tulongest] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [tulongest] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [tulongest] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [tulongest] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [tulongest] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [tulongest] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [tulongest] SET  DISABLE_BROKER 
GO
ALTER DATABASE [tulongest] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [tulongest] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [tulongest] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [tulongest] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [tulongest] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [tulongest] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [tulongest] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [tulongest] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [tulongest] SET  MULTI_USER 
GO
ALTER DATABASE [tulongest] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [tulongest] SET DB_CHAINING OFF 
GO
ALTER DATABASE [tulongest] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [tulongest] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [tulongest] SET DELAYED_DURABILITY = DISABLED 
GO
USE [tulongest]
GO
/****** Object:  Table [dbo].[Data]    Script Date: 2015-03-04 3:31:04 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Data](
	[Id] [int] NOT NULL,
	[HardwareId] [int] NOT NULL,
	[Value] [decimal](18, 0) NOT NULL,
	[Timestamp] [datetime] NOT NULL
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Hardware]    Script Date: 2015-03-04 3:31:04 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Hardware](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[SiteId] [int] NOT NULL,
	[SerialNo] [text] NOT NULL,
 CONSTRAINT [PK_Hardware] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Sites]    Script Date: 2015-03-04 3:31:04 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Sites](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Location] [geometry] NOT NULL,
	[Name] [text] NOT NULL,
	[Address] [text] NOT NULL,
 CONSTRAINT [PK_Site] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
ALTER TABLE [dbo].[Data]  WITH CHECK ADD  CONSTRAINT [FK_Data_Hardware] FOREIGN KEY([HardwareId])
REFERENCES [dbo].[Hardware] ([Id])
GO
ALTER TABLE [dbo].[Data] CHECK CONSTRAINT [FK_Data_Hardware]
GO
ALTER TABLE [dbo].[Hardware]  WITH CHECK ADD  CONSTRAINT [FK_Hardware_Sites] FOREIGN KEY([Id])
REFERENCES [dbo].[Sites] ([Id])
GO
ALTER TABLE [dbo].[Hardware] CHECK CONSTRAINT [FK_Hardware_Sites]
GO
USE [master]
GO
ALTER DATABASE [tulongest] SET  READ_WRITE 
GO
